/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check endpoint
         * @description Returns the current status of the API
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all courses
         * @description Returns a summary of every imported course, for the catalog page. Archived modules/lessons are excluded from moduleCount/lessonCount.
         */
        get: operations["listCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a course's full table of contents
         * @description Returns the course, its tracks, and every non-archived module with its non-archived lessons, in manifest order — enough to render a full table of contents.
         */
        get: operations["getCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}/lessons/{lessonSlug}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark or update a lesson's progress for the current actor
         * @description Upserts lesson_progress for the actor. Idempotent: marking a lesson complete more than once leaves exactly one lesson_progress row and emits exactly one lesson_completed activity event. Only lessons of kind "lesson" may be marked complete through this endpoint — exercises complete on submission and quizzes complete on passing, in later phases; requesting state "complete" against either kind returns 409.
         */
        post: operations["upsertLessonProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the actor's progress summary for a course
         * @description Returns the course's total non-archived lesson count, how many the actor has completed, the completion percent, and each lesson's individual state. Archived lessons never count toward the totals.
         */
        get: operations["getCourseProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}/lessons/{lessonSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a lesson within a course
         * @description Retrieves a lesson with all its blocks, plus prev/next navigation stubs computed across the whole course in manifest order (not just within the lesson's module). An archived lesson (or a lesson whose module is archived) is not reachable here and returns 404.
         */
        get: operations["getCourseLesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description API health check response */
        HealthStatus: {
            /** @description The status of the API (typically "ok") */
            status: string;
        };
        /** @description A prose (narrative) content block with rendered HTML */
        ProseBlock: {
            /**
             * @description The block type discriminator (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "prose";
            /** @description The HTML-rendered content of the prose block */
            html: string;
        };
        /** @description A code block with syntax highlighting metadata */
        CodeBlock: {
            /**
             * @description The block type discriminator (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "code";
            /** @description The programming language or syntax identifier (null if not specified) */
            lang?: ((string | null) | null) | null;
            /** @description The raw source code */
            source: string;
        };
        /** @description A content block, which may be prose or code */
        Block: components["schemas"]["ProseBlock"] | components["schemas"]["CodeBlock"];
        /** @description A minimal pointer to an adjacent lesson, for prev/next navigation. */
        LessonNavStub: {
            /** @description The adjacent lesson's slug (unique within the course) */
            slug: string;
            /** @description The adjacent lesson's title */
            title: string;
        };
        /** @description A lesson containing a title, structured blocks, and whole-course navigation. */
        Lesson: {
            /** @description The URL-friendly identifier for the lesson, unique within its course */
            slug: string;
            /** @description The human-readable title of the lesson */
            title: string;
            /**
             * @description The lesson's kind
             * @enum {string}
             */
            kind: "lesson" | "exercise" | "quiz";
            /** @description The key of the track (lens) this lesson belongs to, or null */
            track: ((string | null) | null) | null;
            /** @description Estimated minutes to complete the lesson, or null if not specified */
            estimateMinutes: ((number | null) | null) | null;
            /** @description The ordered array of content blocks */
            blocks: components["schemas"]["Block"][];
            /** @description The previous lesson in the whole course, in manifest order, or null if this is the first lesson. */
            prev: components["schemas"]["LessonNavStub"] | null;
            /** @description The next lesson in the whole course, in manifest order, or null if this is the last lesson. */
            next: components["schemas"]["LessonNavStub"] | null;
            /** @description The actor's progress on this lesson, or null if they have never interacted with it. */
            progress: components["schemas"]["LessonProgress"] | null;
        };
        /** @description A course track (lens) — a hue-owning grouping lessons can belong to. */
        Track: {
            /** @description The track's stable key, referenced by lessons */
            key: string;
            /** @description The human-readable track name */
            name: string;
            /**
             * @description The one hue this track owns
             * @enum {string}
             */
            hue: "blue" | "teal" | "ochre" | "maroon" | "slate";
            /** @description A short description of the track, or null */
            blurb: ((string | null) | null) | null;
        };
        /** @description A lesson as it appears in a course's table of contents. */
        LessonSummary: {
            /** @description The lesson's slug, unique within its course */
            slug: string;
            /** @description The lesson's title */
            title: string;
            /**
             * @description The lesson's kind
             * @enum {string}
             */
            kind: "lesson" | "exercise" | "quiz";
            /** @description The lesson's position within its module (manifest order) */
            position: number;
            /** @description The key of the track (lens) this lesson belongs to, or null */
            track: ((string | null) | null) | null;
            /** @description Estimated minutes to complete the lesson, or null if not specified */
            estimateMinutes: ((number | null) | null) | null;
        };
        /** @description A course module and its ordered, non-archived lessons. */
        CourseModule: {
            /** @description The module's stable key */
            key: string;
            /** @description The module's title */
            title: string;
            /** @description The module's position within the course (manifest order) */
            position: number;
            /** @description The module's non-archived lessons, in manifest order */
            lessons: components["schemas"]["LessonSummary"][];
        };
        /** @description A course as it appears in the catalog listing. */
        CourseSummary: {
            /** @description The course's globally-unique slug */
            slug: string;
            /** @description The course's title */
            title: string;
            /** @description The course's subtitle, or null */
            subtitle: ((string | null) | null) | null;
            /** @description The course's description, or null */
            description: ((string | null) | null) | null;
            /** @description The course's tags */
            tags: string[];
            /** @description The count of the course's non-archived modules */
            moduleCount: number;
            /** @description The count of the course's non-archived lessons */
            lessonCount: number;
        };
        /** @description A course's full table of contents. */
        CourseDetail: {
            /** @description The course's globally-unique slug */
            slug: string;
            /** @description The course's title */
            title: string;
            /** @description The course's subtitle, or null */
            subtitle: ((string | null) | null) | null;
            /** @description The course's description, or null */
            description: ((string | null) | null) | null;
            /** @description The course's tags */
            tags: string[];
            /** @description The course's tracks (lenses) */
            tracks: components["schemas"]["Track"][];
            /** @description The course's non-archived modules, in manifest order */
            modules: components["schemas"]["CourseModule"][];
        };
        /**
         * @description The state a lesson_progress row can be written with.
         * @enum {string}
         */
        ProgressState: "in_progress" | "complete";
        /** @description The actor's progress on a lesson, embedded in the lesson response so a reader can resume. */
        LessonProgress: {
            state: components["schemas"]["ProgressState"];
            /** @description An opaque string the reader uses to resume, or null. */
            lastPosition: ((string | null) | null) | null;
        };
        /** @description The full lesson_progress row for the actor, after an upsert. */
        LessonProgressDetail: {
            state: components["schemas"]["ProgressState"];
            /** @description An opaque string the reader uses to resume, or null. */
            lastPosition: ((string | null) | null) | null;
            /** @description Total seconds spent, as last recorded. */
            secondsSpent: number;
            /**
             * Format: date-time
             * @description When the lesson was first marked complete, or null.
             */
            completedAt: ((string | null) | null) | null;
            /**
             * Format: date-time
             * @description When this progress row was last written.
             */
            updatedAt: string;
        };
        /** @description A partial update to the actor's progress on a lesson. */
        ProgressUpsertRequest: {
            state?: components["schemas"]["ProgressState"];
            /** @description An opaque string the reader uses to resume. */
            lastPosition?: ((string | null) | null) | null;
            /** @description Total seconds spent on the lesson, replacing the stored value. */
            secondsSpent?: number;
        };
        /**
         * @description A lesson's progress state as it appears in a course summary. Unlike ProgressState, includes "not_started" for lessons with no lesson_progress row yet.
         * @enum {string}
         */
        CourseProgressLessonState: "not_started" | "in_progress" | "complete";
        /** @description One lesson's state within a course progress summary. */
        CourseProgressLesson: {
            /** @description The lesson's slug, unique within its course */
            slug: string;
            /**
             * @description The lesson's kind
             * @enum {string}
             */
            kind: "lesson" | "exercise" | "quiz";
            state: components["schemas"]["CourseProgressLessonState"];
        };
        /** @description The actor's progress summary for a course. Archived lessons never count toward totalLessons/completedLessons. */
        CourseProgressSummary: {
            /** @description Count of the course's non-archived lessons. */
            totalLessons: number;
            /** @description Count of those lessons the actor has completed. */
            completedLessons: number;
            /** @description completedLessons / totalLessons as a rounded percent (0 if totalLessons is 0). */
            percent: number;
            /** @description Every non-archived lesson's individual state, in manifest order. */
            lessons: components["schemas"]["CourseProgressLesson"][];
        };
        /** @description An error response */
        Error: {
            /** @description A human-readable error message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    listCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseSummary"][];
                };
            };
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    upsertLessonProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
                /** @description The lesson slug (unique within the course) */
                lessonSlug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProgressUpsertRequest"];
            };
        };
        responses: {
            /** @description Progress recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonProgressDetail"];
                };
            };
            /** @description Course or lesson not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The lesson's kind cannot be marked complete directly (only kind "lesson" can — exercises and quizzes complete through other mechanisms). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCourseProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseProgressSummary"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCourseLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
                /** @description The lesson slug (unique within the course) */
                lessonSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lesson found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            /** @description Course or lesson not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
