/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check endpoint
         * @description Returns the current status of the API
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all courses
         * @description Returns a summary of every imported course, for the catalog page. Archived modules/lessons are excluded from moduleCount/lessonCount.
         */
        get: operations["listCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a course's full table of contents
         * @description Returns the course, its tracks, and every non-archived module with its non-archived lessons, in manifest order — enough to render a full table of contents.
         */
        get: operations["getCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}/lessons/{lessonSlug}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark or update a lesson's progress for the current actor
         * @description Upserts lesson_progress for the actor. Idempotent: marking a lesson complete more than once leaves exactly one lesson_progress row and emits exactly one lesson_completed activity event. Only lessons of kind "lesson" may be marked complete through this endpoint — exercises complete on submission and quizzes complete on passing, in later phases; requesting state "complete" against either kind returns 409.
         */
        post: operations["upsertLessonProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the actor's progress summary for a course
         * @description Returns the course's total non-archived lesson count, how many the actor has completed, the completion percent, and each lesson's individual state. Archived lessons never count toward the totals.
         */
        get: operations["getCourseProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current actor's profile
         * @description Returns the actor's id, display name, and effective timezone. `timezoneSource` is "default" when `users.timezone` is null and the UTC fallback (design §15) is being used, "set" otherwise — so the UI can prompt for confirmation only when a real value hasn't been chosen yet.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the current actor's timezone
         * @description Sets `users.timezone`. The value must be a real IANA time zone name (validated via Intl) — storing anything else would silently break every heatmap/streak bucket query, which key off this column. Changing timezone shifts historical day buckets and may retroactively alter a streak (design §15); badges already earned are never revoked.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v1/me/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The actor's recent activity feed
         * @description Recent activity_events for the actor, newest first, with enough joined course/lesson context to render (design §10). course/lesson are null for event types not tied to either.
         */
        get: operations["getMyActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The actor's activity heatmap
         * @description A contiguous run of local calendar days (design §15: bucketed in the actor's IANA timezone, falling back to UTC when unset) with an activity count each — days with zero activity are present with count 0, never omitted, so the UI never has to infer a gap. Also returns current/longest streak (design §10), computed fresh from activity_events, not a stored counter.
         */
        get: operations["getMyHeatmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}/lessons/{lessonSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a lesson within a course
         * @description Retrieves a lesson with all its blocks, plus prev/next navigation stubs computed across the whole course in manifest order (not just within the lesson's module). An archived lesson (or a lesson whose module is archived) is not reachable here and returns 404.
         */
        get: operations["getCourseLesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description API health check response */
        HealthStatus: {
            /** @description The status of the API (typically "ok") */
            status: string;
        };
        /** @description A prose (narrative) content block with rendered HTML */
        ProseBlock: {
            /**
             * @description The block type discriminator (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "prose";
            /** @description The HTML-rendered content of the prose block */
            html: string;
        };
        /** @description A code block with syntax highlighting metadata */
        CodeBlock: {
            /**
             * @description The block type discriminator (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "code";
            /** @description The programming language or syntax identifier (null if not specified) */
            lang?: ((string | null) | null) | null;
            /** @description The raw source code */
            source: string;
        };
        /** @description A content block, which may be prose or code */
        Block: components["schemas"]["ProseBlock"] | components["schemas"]["CodeBlock"];
        /** @description A minimal pointer to an adjacent lesson, for prev/next navigation. */
        LessonNavStub: {
            /** @description The adjacent lesson's slug (unique within the course) */
            slug: string;
            /** @description The adjacent lesson's title */
            title: string;
        };
        /** @description A lesson containing a title, structured blocks, and whole-course navigation. */
        Lesson: {
            /** @description The URL-friendly identifier for the lesson, unique within its course */
            slug: string;
            /** @description The human-readable title of the lesson */
            title: string;
            /**
             * @description The lesson's kind
             * @enum {string}
             */
            kind: "lesson" | "exercise" | "quiz";
            /** @description The key of the track (lens) this lesson belongs to, or null */
            track: ((string | null) | null) | null;
            /** @description Estimated minutes to complete the lesson, or null if not specified */
            estimateMinutes: ((number | null) | null) | null;
            /** @description The ordered array of content blocks */
            blocks: components["schemas"]["Block"][];
            /** @description The previous lesson in the whole course, in manifest order, or null if this is the first lesson. */
            prev: components["schemas"]["LessonNavStub"] | null;
            /** @description The next lesson in the whole course, in manifest order, or null if this is the last lesson. */
            next: components["schemas"]["LessonNavStub"] | null;
            /** @description The actor's progress on this lesson, or null if they have never interacted with it. */
            progress: components["schemas"]["LessonProgress"] | null;
        };
        /** @description A course track (lens) — a hue-owning grouping lessons can belong to. */
        Track: {
            /** @description The track's stable key, referenced by lessons */
            key: string;
            /** @description The human-readable track name */
            name: string;
            /**
             * @description The one hue this track owns
             * @enum {string}
             */
            hue: "blue" | "teal" | "ochre" | "maroon" | "slate";
            /** @description A short description of the track, or null */
            blurb: ((string | null) | null) | null;
        };
        /** @description A lesson as it appears in a course's table of contents. */
        LessonSummary: {
            /** @description The lesson's slug, unique within its course */
            slug: string;
            /** @description The lesson's title */
            title: string;
            /**
             * @description The lesson's kind
             * @enum {string}
             */
            kind: "lesson" | "exercise" | "quiz";
            /** @description The lesson's position within its module (manifest order) */
            position: number;
            /** @description The key of the track (lens) this lesson belongs to, or null */
            track: ((string | null) | null) | null;
            /** @description Estimated minutes to complete the lesson, or null if not specified */
            estimateMinutes: ((number | null) | null) | null;
        };
        /** @description A course module and its ordered, non-archived lessons. */
        CourseModule: {
            /** @description The module's stable key */
            key: string;
            /** @description The module's title */
            title: string;
            /** @description The module's position within the course (manifest order) */
            position: number;
            /** @description The module's non-archived lessons, in manifest order */
            lessons: components["schemas"]["LessonSummary"][];
        };
        /** @description A course as it appears in the catalog listing. */
        CourseSummary: {
            /** @description The course's globally-unique slug */
            slug: string;
            /** @description The course's title */
            title: string;
            /** @description The course's subtitle, or null */
            subtitle: ((string | null) | null) | null;
            /** @description The course's description, or null */
            description: ((string | null) | null) | null;
            /** @description The course's tags */
            tags: string[];
            /** @description The count of the course's non-archived modules */
            moduleCount: number;
            /** @description The count of the course's non-archived lessons */
            lessonCount: number;
        };
        /** @description A course's full table of contents. */
        CourseDetail: {
            /** @description The course's globally-unique slug */
            slug: string;
            /** @description The course's title */
            title: string;
            /** @description The course's subtitle, or null */
            subtitle: ((string | null) | null) | null;
            /** @description The course's description, or null */
            description: ((string | null) | null) | null;
            /** @description The course's tags */
            tags: string[];
            /** @description The course's tracks (lenses) */
            tracks: components["schemas"]["Track"][];
            /** @description The course's non-archived modules, in manifest order */
            modules: components["schemas"]["CourseModule"][];
        };
        /**
         * @description The state a lesson_progress row can be written with.
         * @enum {string}
         */
        ProgressState: "in_progress" | "complete";
        /** @description The actor's progress on a lesson, embedded in the lesson response so a reader can resume. */
        LessonProgress: {
            state: components["schemas"]["ProgressState"];
            /** @description An opaque string the reader uses to resume, or null. */
            lastPosition: ((string | null) | null) | null;
        };
        /** @description The full lesson_progress row for the actor, after an upsert. */
        LessonProgressDetail: {
            state: components["schemas"]["ProgressState"];
            /** @description An opaque string the reader uses to resume, or null. */
            lastPosition: ((string | null) | null) | null;
            /** @description Total seconds spent, as last recorded. */
            secondsSpent: number;
            /**
             * Format: date-time
             * @description When the lesson was first marked complete, or null.
             */
            completedAt: ((string | null) | null) | null;
            /**
             * Format: date-time
             * @description When this progress row was last written.
             */
            updatedAt: string;
        };
        /** @description A partial update to the actor's progress on a lesson. */
        ProgressUpsertRequest: {
            state?: components["schemas"]["ProgressState"];
            /** @description An opaque string the reader uses to resume. */
            lastPosition?: ((string | null) | null) | null;
            /** @description Total seconds spent on the lesson, replacing the stored value. */
            secondsSpent?: number;
        };
        /**
         * @description A lesson's progress state as it appears in a course summary. Unlike ProgressState, includes "not_started" for lessons with no lesson_progress row yet.
         * @enum {string}
         */
        CourseProgressLessonState: "not_started" | "in_progress" | "complete";
        /** @description One lesson's state within a course progress summary. */
        CourseProgressLesson: {
            /** @description The lesson's slug, unique within its course */
            slug: string;
            /**
             * @description The lesson's kind
             * @enum {string}
             */
            kind: "lesson" | "exercise" | "quiz";
            state: components["schemas"]["CourseProgressLessonState"];
        };
        /** @description The actor's progress summary for a course. Archived lessons never count toward totalLessons/completedLessons. */
        CourseProgressSummary: {
            /** @description Count of the course's non-archived lessons. */
            totalLessons: number;
            /** @description Count of those lessons the actor has completed. */
            completedLessons: number;
            /** @description completedLessons / totalLessons as a rounded percent (0 if totalLessons is 0). */
            percent: number;
            /** @description Every non-archived lesson's individual state, in manifest order. */
            lessons: components["schemas"]["CourseProgressLesson"][];
        };
        /** @description An error response */
        Error: {
            /** @description A human-readable error message */
            message: string;
        };
        /**
         * @description "set" when users.timezone holds a real value the actor chose; "default" when it is null and the UTC fallback (design §15) is in effect.
         * @enum {string}
         */
        TimezoneSource: "set" | "default";
        /** @description The current actor's profile. */
        Me: {
            /** @description The actor's user id */
            id: string;
            /** @description The actor's display name, or null if unset */
            displayName: ((string | null) | null) | null;
            /** @description The actor's effective IANA timezone — their stored value, or "UTC" when unset (design §15). */
            timezone: string;
            timezoneSource: components["schemas"]["TimezoneSource"];
        };
        /** @description A request to set the actor's timezone. */
        MeUpdateRequest: {
            /** @description A real IANA time zone name (e.g. "America/Denver"). */
            timezone: string;
        };
        /**
         * @description The kind of activity_events row (design §10).
         * @enum {string}
         */
        ActivityEventType: "lesson_completed" | "exercise_submitted" | "exercise_returned" | "quiz_passed" | "course_enrolled" | "course_completed" | "degree_earned" | "badge_awarded";
        /** @description Minimal course context for rendering a feed entry. */
        ActivityCourseRef: {
            /** @description The course's slug */
            slug: string;
            /** @description The course's title */
            title: string;
        };
        /** @description Minimal lesson context for rendering a feed entry. */
        ActivityLessonRef: {
            /** @description The lesson's slug, unique within its course */
            slug: string;
            /** @description The lesson's title */
            title: string;
        };
        /** @description One activity_events row, joined with enough context to render. */
        ActivityEvent: {
            type: components["schemas"]["ActivityEventType"];
            /**
             * Format: date-time
             * @description When the event occurred, in UTC.
             */
            occurredAt: string;
            /** @description The related course, or null if this event type has none. */
            course: components["schemas"]["ActivityCourseRef"] | null;
            /** @description The related lesson, or null if this event type has none. */
            lesson: components["schemas"]["ActivityLessonRef"] | null;
        };
        /** @description One local calendar day's activity count. */
        HeatmapDay: {
            /** @description The local calendar date, YYYY-MM-DD. */
            date: string;
            /** @description Number of activity_events on this local day. */
            count: number;
        };
        /** @description The actor's activity heatmap: a contiguous run of local days plus derived streaks (design §10, §15). */
        Heatmap: {
            /** @description The timezone the days were bucketed in. */
            timezone: string;
            timezoneSource: components["schemas"]["TimezoneSource"];
            /** @description Contiguous local days, oldest first, ending today. */
            days: components["schemas"]["HeatmapDay"][];
            /** @description The highest single-day count in `days`, for scaling the intensity ramp. */
            maxCount: number;
            /** @description Current streak in local calendar days, computed fresh from activity_events. */
            currentStreak: number;
            /** @description Longest streak ever, in local calendar days, computed fresh from activity_events. */
            longestStreak: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    listCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseSummary"][];
                };
            };
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    upsertLessonProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
                /** @description The lesson slug (unique within the course) */
                lessonSlug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProgressUpsertRequest"];
            };
        };
        responses: {
            /** @description Progress recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonProgressDetail"];
                };
            };
            /** @description Course or lesson not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The lesson's kind cannot be marked complete directly (only kind "lesson" can — exercises and quizzes complete through other mechanisms). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCourseProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseProgressSummary"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The actor's profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdateRequest"];
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description timezone is missing or not a real IANA zone name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMyActivity: {
        parameters: {
            query?: {
                /** @description Max events to return. Defaults to 20, clamped to [1, 100]. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The activity feed, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityEvent"][];
                };
            };
        };
    };
    getMyHeatmap: {
        parameters: {
            query?: {
                /** @description Trailing window size in weeks (7 days each), ending today. Defaults to 53, clamped to [1, 53]; narrower clients request fewer (design §10: ~13 on phone, ~26 on tablet). */
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The heatmap */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Heatmap"];
                };
            };
        };
    };
    getCourseLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
                /** @description The lesson slug (unique within the course) */
                lessonSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lesson found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            /** @description Course or lesson not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
