/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check endpoint
         * @description Returns the current status of the API
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description Verifies the credential and, on success, starts a session: sets the httpOnly access-token and refresh-token cookies (design §13) and records an `auth.login` audit_log row. There is no account oracle (design §13/auth.ts) — an unknown email, a wrong password, and an account with no credential (`password_hash is null`) all produce the identical 401 body, the identical status, and the same Argon2id work. Rate-limited per IP and per account, with doubling backoff (design §13); a locked-out attempt is refused with 429 before the lookup or the hash, so lockout cannot be used as a CPU sink either.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token and mint a new access token
         * @description Reads the `learn_rt` cookie, rotates it, and re-reads the caller's roles from the database (design §13: "role is in the token for cheap reads; privileged mutations re-check the database, so a demotion takes effect immediately rather than at next refresh" — refresh is the other place a stale role claim gets a chance to correct itself). Presenting an already-spent refresh token is treated as token theft (design §13 reuse detection): the whole token family is revoked, an `auth.refresh_reuse_detected` audit_log row is written, and both cookies are cleared, killing the session everywhere until the next password login. Every failure — missing cookie, unknown token, expired token, revoked token, or reuse — answers with the identical 401 body, and always clears both cookies, so a client holding a dead token is never left retrying it forever.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session
         * @description Revokes the session named by the `learn_rt` cookie (if any) and clears both cookies. Keyed off the refresh cookie rather than the actor so signing out still works once the access token has already expired — exactly when a visitor reaches for this control. Always succeeds, including with no cookie at all: signing out is never an error.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End every session on every device
         * @description Revokes every refresh-token family belonging to the caller (design §13's "sign out everywhere" control) and clears the caller's own cookies. Gated by `session:revoke:all`, decided by `can()` like every other route — an unauthenticated caller is refused with 403, not a locally written 401 check (CLAUDE.md rule 2).
         */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all courses
         * @description Returns a summary of every imported course, for the catalog page. Archived modules/lessons are excluded from moduleCount/lessonCount.
         */
        get: operations["listCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a course's full table of contents
         * @description Returns the course, its tracks, and every non-archived module with its non-archived lessons, in manifest order — enough to render a full table of contents.
         */
        get: operations["getCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Publish/set a course's visibility, or transfer its ownership
         * @description Accepts `visibility` and/or `ownerId`. `visibility` is gated by `course:visibility:set` (design §12: the owning teacher, or an admin override); `ownerId` is gated by `course:ownership:transfer` (admin only). Either field may be omitted, but at least one is required. Neither write happens unless its own permission check passes — a request naming both fields where the actor may only change one is refused entirely, before anything is written.
         */
        patch: operations["patchCourse"];
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}/manage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The course's settings view (owner/admin only)
         * @description Gated by `course:manage:read`, unconditional on visibility — this is how a teacher-only owner (no student role) reads their own course, and how an admin reaches any course regardless of visibility. A denial is always reported as 404, never 403: this endpoint has nothing to disclose to anyone it is not the settings screen for.
         */
        get: operations["getCourseManage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}/enrolments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Self-enrol in a course
         * @description Gated by `course:enrol` (design §12): allowed in an `open` course, or in any course the actor owns (the self-enrollment design §5 describes for a teacher's own course, published or not). `restricted` refuses self-enrolment for anyone but the owner — Phase 13's course invites are not built yet. Idempotent: enrolling twice leaves exactly one row, `status = 'active'`.
         */
        post: operations["createEnrolment"];
        /**
         * Un-enrol from a course
         * @description Soft delete: the enrollment row's `status` flips to `withdrawn` rather than being removed (design §7: user tables are source of truth, nothing under `users` is recoverable). Re-enrolling flips it back to `active` on the same row. A harmless no-op if the actor was never enrolled.
         */
        delete: operations["deleteEnrolment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}/lessons/{lessonSlug}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark or update a lesson's progress for the current actor
         * @description Upserts lesson_progress for the actor. Idempotent: marking a lesson complete more than once leaves exactly one lesson_progress row and emits exactly one lesson_completed activity event. Only lessons of kind "lesson" may be marked complete through this endpoint — exercises complete on submission and quizzes complete on passing, in later phases; requesting state "complete" against either kind returns 409.
         */
        post: operations["upsertLessonProgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}/lessons/{lessonSlug}/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit and score a quiz attempt
         * @description Scores `answers` server-side against the lesson's stored quiz block (design §9.1: quizzes are machine-scored, and complete ONLY by passing — never by direct completion, which 409s on POST .../progress for kind "quiz"). Always records a quiz_attempts row, win or lose; retaking is allowed. On a pass, marks the lesson complete and emits a quiz_passed activity event — idempotent, so passing more than once never emits a second event or re-completes an already-complete lesson. Only lessons of kind "quiz" may be scored here; any other kind returns 409.
         */
        post: operations["submitQuizAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the actor's progress summary for a course
         * @description Returns the course's total non-archived lesson count, how many the actor has completed, the completion percent, and each lesson's individual state. Archived lessons never count toward the totals.
         */
        get: operations["getCourseProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current actor's profile
         * @description Returns the actor's id, display name, and effective timezone. `timezoneSource` is "default" when `users.timezone` is null and the UTC fallback (design §15) is being used, "set" otherwise — so the UI can prompt for confirmation only when a real value hasn't been chosen yet.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the current actor's timezone
         * @description Sets `users.timezone`. The value must be a real IANA time zone name (validated via Intl) — storing anything else would silently break every heatmap/streak bucket query, which key off this column. Changing timezone shifts historical day buckets and may retroactively alter a streak (design §15); badges already earned are never revoked.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v1/me/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The actor's recent activity feed
         * @description Recent activity_events for the actor, newest first, with enough joined course/lesson context to render (design §10). course/lesson are null for event types not tied to either.
         */
        get: operations["getMyActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The actor's activity heatmap
         * @description A contiguous run of local calendar days (design §15: bucketed in the actor's IANA timezone, falling back to UTC when unset) with an activity count each — days with zero activity are present with count 0, never omitted, so the UI never has to infer a gap. Also returns current/longest streak (design §10), computed fresh from activity_events, not a stored counter.
         */
        get: operations["getMyHeatmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{courseSlug}/lessons/{lessonSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a lesson within a course
         * @description Retrieves a lesson with all its blocks, plus prev/next navigation stubs computed across the whole course in manifest order (not just within the lesson's module). An archived lesson (or a lesson whose module is archived) is not reachable here and returns 404.
         */
        get: operations["getCourseLesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a content repo (streamed)
         * @description UNAUTHENTICATED UNTIL PHASE 6 (see the route source for the full note) — acceptable only because the app is LAN-only until Gate 6. Clones `url` at `ref` (default the repo's default branch), validates its manifest and lessons, then writes it in one transaction (design §8). Runs synchronously — there is deliberately no job queue (design §4) — and streams progress as it happens, one JSON object per line (newline-delimited JSON, not a single JSON body), `Content-Type: application/x-ndjson`. Every line matches ImportProgressEvent. A `file://` URL is always refused: the clone step never receives the internal opt-in that would allow one. On failure the LAST line's `problems` array is the same file:line problem list the CLI prints (design §8: "error quality is the authoring experience"), and an `import_runs` row is written either way — a failed import is not silently dropped from history.
         */
        post: operations["createAdminImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/import-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Import run history
         * @description UNAUTHENTICATED UNTIL PHASE 6, same note as POST /api/v1/admin/imports. Every import_runs row, newest first, with the repo URL it came from (if any — a local-directory import has none) and, for a finished run, either its per-entity counts or its error/problem list.
         */
        get: operations["listAdminImportRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * First-run setup status
         * @description Whether this instance has been claimed yet (design §5.2). The bootstrap wizard calls this to decide whether to show itself. It reveals one bit, the same bit the 410 below already reveals.
         */
        get: operations["getSetupStatus"];
        put?: never;
        /**
         * Claim the instance (first-run bootstrap)
         * @description The single exception to invite-only registration (design §13). Gated by the one-time setup token printed to the container logs on boot — the plaintext is never stored, only its SHA-256.
         *     Creates a LINKED PAIR (design §5.2): the operator account, holding `admin` and nothing else because admin is exclusive (design §5.1), and a student account, linked by `users.operator_for`. Both accounts and the claim itself are one transaction.
         *     The claim is atomic: `UPDATE instance_state SET bootstrapped_at = now() WHERE bootstrapped_at IS NULL`. Two simultaneous requests yield exactly one 201; the loser gets 409. Once claimed, the route is permanently closed and answers 410 — recorded in `instance_state`, not merely hidden from the UI.
         */
        post: operations["createSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description API health check response */
        HealthStatus: {
            /** @description The status of the API (typically "ok") */
            status: string;
        };
        /** @description A prose (narrative) content block with rendered HTML */
        ProseBlock: {
            /**
             * @description The block type discriminator (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "prose";
            /** @description The HTML-rendered content of the prose block */
            html: string;
        };
        /** @description A note attached to a source line or inclusive line range. Author annotations are authored in the content repo as in-source marker comments and stripped from the stored source at import; student annotations are created against an exercise. Exactly one of `line` or `lines` is present. */
        CodeAnnotation: {
            /** @description The single 1-indexed source line this attaches to. */
            line?: number;
            /** @description An inclusive [start, end] 1-indexed range. */
            lines?: number[];
            /** @description Optional track id, matching a track's id in course.yaml. */
            track?: string;
            body: string;
        };
        /** @description A code block with syntax highlighting metadata */
        CodeBlock: {
            /**
             * @description The block type discriminator (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "code";
            /** @description The programming language or syntax identifier (null if not specified) */
            lang?: ((string | null) | null) | null;
            /** @description The raw source code */
            source: string;
            /** @description Annotations attached to lines of this block. Present on lessons whose content carries author notes, and on exercises. */
            annotations?: components["schemas"]["CodeAnnotation"][];
        };
        /** @description One answer choice for a quiz question, as served to the browser. Deliberately has no `correct` field — the API strips it before a lesson's blocks are serialized (design §9.1: quizzes are machine-scored server-side), so a reader checking page source cannot find the answer key. The stored form (used only by the scoring endpoint, never returned) does carry it. */
        QuizChoice: {
            /** @description The choice's display text */
            text: string;
        };
        /** @description One quiz question, as served to the browser. */
        QuizQuestion: {
            /** @description The question text */
            prompt: string;
            /** @description The key of the track (lens) this question belongs to, or null */
            track: ((string | null) | null) | null;
            /** @description The question's answer choices, in order (referenced by index when submitting) */
            choices: components["schemas"]["QuizChoice"][];
        };
        /** @description A quiz block (design §6.3: a tagged fenced block with YAML). `pass` is the passing threshold — the fraction of questions that must be answered correctly. Scoring never happens in this response; submit answers to POST .../quiz instead. */
        QuizBlock: {
            /**
             * @description The block type discriminator (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "quiz";
            /** @description Passing threshold as a fraction of correctly-answered questions, e.g. 0.7 */
            pass: number;
            questions: components["schemas"]["QuizQuestion"][];
        };
        /** @description A content block, which may be prose, code, or a quiz */
        Block: components["schemas"]["ProseBlock"] | components["schemas"]["CodeBlock"] | components["schemas"]["QuizBlock"];
        /** @description A minimal pointer to an adjacent lesson, for prev/next navigation. */
        LessonNavStub: {
            /** @description The adjacent lesson's slug (unique within the course) */
            slug: string;
            /** @description The adjacent lesson's title */
            title: string;
        };
        /** @description A lesson containing a title, structured blocks, and whole-course navigation. */
        Lesson: {
            /** @description The URL-friendly identifier for the lesson, unique within its course */
            slug: string;
            /** @description The human-readable title of the lesson */
            title: string;
            /**
             * @description The lesson's kind
             * @enum {string}
             */
            kind: "lesson" | "exercise" | "quiz";
            /** @description The key of the track (lens) this lesson belongs to, or null */
            track: ((string | null) | null) | null;
            /** @description Estimated minutes to complete the lesson, or null if not specified */
            estimateMinutes: ((number | null) | null) | null;
            /** @description The ordered array of content blocks */
            blocks: components["schemas"]["Block"][];
            /** @description The previous lesson in the whole course, in manifest order, or null if this is the first lesson. */
            prev: components["schemas"]["LessonNavStub"] | null;
            /** @description The next lesson in the whole course, in manifest order, or null if this is the last lesson. */
            next: components["schemas"]["LessonNavStub"] | null;
            /** @description The actor's progress on this lesson, or null if they have never interacted with it. */
            progress: components["schemas"]["LessonProgress"] | null;
        };
        /** @description A course track (lens) — a hue-owning grouping lessons can belong to. */
        Track: {
            /** @description The track's stable key, referenced by lessons */
            key: string;
            /** @description The human-readable track name */
            name: string;
            /**
             * @description The one hue this track owns
             * @enum {string}
             */
            hue: "blue" | "teal" | "ochre" | "maroon" | "slate";
            /** @description A short description of the track, or null */
            blurb: ((string | null) | null) | null;
        };
        /** @description A lesson as it appears in a course's table of contents. */
        LessonSummary: {
            /** @description The lesson's slug, unique within its course */
            slug: string;
            /** @description The lesson's title */
            title: string;
            /**
             * @description The lesson's kind
             * @enum {string}
             */
            kind: "lesson" | "exercise" | "quiz";
            /** @description The lesson's position within its module (manifest order) */
            position: number;
            /** @description The key of the track (lens) this lesson belongs to, or null */
            track: ((string | null) | null) | null;
            /** @description Estimated minutes to complete the lesson, or null if not specified */
            estimateMinutes: ((number | null) | null) | null;
        };
        /** @description A course module and its ordered, non-archived lessons. */
        CourseModule: {
            /** @description The module's stable key */
            key: string;
            /** @description The module's title */
            title: string;
            /** @description The module's position within the course (manifest order) */
            position: number;
            /** @description The module's non-archived lessons, in manifest order */
            lessons: components["schemas"]["LessonSummary"][];
        };
        /**
         * @description design §12. `open` — listed, any student may self-enrol. `restricted` — listed, self-enrolment needs a teacher's invite. `hidden` — absent from the catalog; a direct fetch 404s for anyone but the owner or an admin. New courses land `hidden`; re-import never changes it.
         * @enum {string}
         */
        CourseVisibility: "open" | "restricted" | "hidden";
        /** @description A course as it appears in the catalog listing. */
        CourseSummary: {
            /** @description The course's globally-unique slug */
            slug: string;
            /** @description The course's title */
            title: string;
            /** @description The course's subtitle, or null */
            subtitle: ((string | null) | null) | null;
            /** @description The course's description, or null */
            description: ((string | null) | null) | null;
            /** @description The course's tags */
            tags: string[];
            /** @description The count of the course's non-archived modules */
            moduleCount: number;
            /** @description The count of the course's non-archived lessons */
            lessonCount: number;
            visibility: components["schemas"]["CourseVisibility"];
        };
        /** @description A course's full table of contents. */
        CourseDetail: {
            /** @description The course's globally-unique slug */
            slug: string;
            /** @description The course's title */
            title: string;
            /** @description The course's subtitle, or null */
            subtitle: ((string | null) | null) | null;
            /** @description The course's description, or null */
            description: ((string | null) | null) | null;
            /** @description The course's tags */
            tags: string[];
            /** @description The course's tracks (lenses) */
            tracks: components["schemas"]["Track"][];
            /** @description The course's non-archived modules, in manifest order */
            modules: components["schemas"]["CourseModule"][];
            visibility: components["schemas"]["CourseVisibility"];
            /** @description Whether the current actor holds an active enrollment in this course. */
            enrolled: boolean;
            /** @description Whether the current actor may change this course's visibility (course:visibility:set) — drives the web publish control (design plan phase 6 web). Server-computed; the client never re-derives ownership. */
            canPublish: boolean;
        };
        /** @description A course's settings view (GET/PATCH .../manage and .../courses/{slug}), gated by course:manage:read — the owner's/admin's screen, unconditional on visibility. */
        CourseManage: {
            /** @description The course's globally-unique slug */
            slug: string;
            /** @description The course's title */
            title?: string;
            subtitle?: ((string | null) | null) | null;
            description?: ((string | null) | null) | null;
            /** @description courses.owner_id (migration 0007). Null means no teacher owns it. */
            ownerId?: ((string | null) | null) | null;
            visibility: components["schemas"]["CourseVisibility"];
        };
        /** @description At least one of `visibility`/`ownerId` is required. `visibility` is gated by course:visibility:set; `ownerId` (a user id, or null to unassign) is gated by course:ownership:transfer (admin only). */
        CoursePatchRequest: {
            visibility?: components["schemas"]["CourseVisibility"];
            /** @description A user id to make the course's owner, or null to unassign. */
            ownerId?: ((string | null) | null) | null;
        };
        /** @description The actor's enrollment state for one course, after a POST/DELETE. */
        Enrolment: {
            enrolled: boolean;
            /**
             * Format: date-time
             * @description Present on a successful POST; omitted on DELETE.
             */
            enrolledAt?: string;
        };
        /**
         * @description The state a lesson_progress row can be written with.
         * @enum {string}
         */
        ProgressState: "in_progress" | "complete";
        /** @description The actor's progress on a lesson, embedded in the lesson response so a reader can resume. */
        LessonProgress: {
            state: components["schemas"]["ProgressState"];
            /** @description An opaque string the reader uses to resume, or null. */
            lastPosition: ((string | null) | null) | null;
        };
        /** @description The full lesson_progress row for the actor, after an upsert. */
        LessonProgressDetail: {
            state: components["schemas"]["ProgressState"];
            /** @description An opaque string the reader uses to resume, or null. */
            lastPosition: ((string | null) | null) | null;
            /** @description Total seconds spent, as last recorded. */
            secondsSpent: number;
            /**
             * Format: date-time
             * @description When the lesson was first marked complete, or null.
             */
            completedAt: ((string | null) | null) | null;
            /**
             * Format: date-time
             * @description When this progress row was last written.
             */
            updatedAt: string;
        };
        /** @description A partial update to the actor's progress on a lesson. */
        ProgressUpsertRequest: {
            state?: components["schemas"]["ProgressState"];
            /** @description An opaque string the reader uses to resume. */
            lastPosition?: ((string | null) | null) | null;
            /** @description Total seconds spent on the lesson, replacing the stored value. */
            secondsSpent?: number;
        };
        /**
         * @description A lesson's progress state as it appears in a course summary. Unlike ProgressState, includes "not_started" for lessons with no lesson_progress row yet.
         * @enum {string}
         */
        CourseProgressLessonState: "not_started" | "in_progress" | "complete";
        /** @description One lesson's state within a course progress summary. */
        CourseProgressLesson: {
            /** @description The lesson's slug, unique within its course */
            slug: string;
            /**
             * @description The lesson's kind
             * @enum {string}
             */
            kind: "lesson" | "exercise" | "quiz";
            state: components["schemas"]["CourseProgressLessonState"];
        };
        /** @description The actor's progress summary for a course. Archived lessons never count toward totalLessons/completedLessons. */
        CourseProgressSummary: {
            /** @description Count of the course's non-archived lessons. */
            totalLessons: number;
            /** @description Count of those lessons the actor has completed. */
            completedLessons: number;
            /** @description completedLessons / totalLessons as a rounded percent (0 if totalLessons is 0). */
            percent: number;
            /** @description Every non-archived lesson's individual state, in manifest order. */
            lessons: components["schemas"]["CourseProgressLesson"][];
        };
        /** @description One submitted answer, referencing the quiz block by index. */
        QuizAnswerInput: {
            /** @description 0-based index into the quiz block's questions array */
            questionIndex: number;
            /** @description 0-based index into that question's choices array */
            choiceIndex: number;
        };
        /** @description A quiz submission — one answer per attempted question. Unanswered questions may be omitted. */
        QuizSubmitRequest: {
            answers: components["schemas"]["QuizAnswerInput"][];
        };
        /** @description One question's scored outcome. `correctChoiceIndex` is safe to return here (unlike on the lesson response) because scoring has already happened — this is feedback on an attempt, not the pre-attempt answer key. */
        QuizQuestionResult: {
            questionIndex: number;
            track: ((string | null) | null) | null;
            /** @description The choice the actor submitted for this question, or null if unanswered. */
            choiceIndex: ((number | null) | null) | null;
            correctChoiceIndex: number;
            correct: boolean;
        };
        /** @description One track's correct/total count within a single attempt (design §9.1/§9.3). */
        QuizTrackScore: {
            correct: number;
            total: number;
        };
        /** @description A pointer to the quiz_attempts row this submission wrote. */
        QuizAttemptRef: {
            id: string;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description The scored result of a quiz submission (design §9.1). */
        QuizSubmitResult: {
            /** @description Fraction of questions answered correctly, 0-1 */
            score: number;
            passed: boolean;
            /** @description The block's own passing threshold, echoed back for the reader */
            pass: number;
            results: components["schemas"]["QuizQuestionResult"][];
            trackScores: {
                [key: string]: components["schemas"]["QuizTrackScore"];
            };
            attempt: components["schemas"]["QuizAttemptRef"];
        };
        /** @description An error response */
        Error: {
            /** @description A human-readable error message */
            message: string;
        };
        /**
         * @description "set" when users.timezone holds a real value the actor chose; "default" when it is null and the UTC fallback (design §15) is in effect.
         * @enum {string}
         */
        TimezoneSource: "set" | "default";
        /** @description The current actor's profile. */
        Me: {
            /** @description The actor's user id */
            id: string;
            /** @description The actor's display name, or null if unset */
            displayName: ((string | null) | null) | null;
            /** @description The actor's effective IANA timezone — their stored value, or "UTC" when unset (design §15). */
            timezone: string;
            timezoneSource: components["schemas"]["TimezoneSource"];
        };
        /** @description A request to set the actor's timezone. */
        MeUpdateRequest: {
            /** @description A real IANA time zone name (e.g. "America/Denver"). */
            timezone: string;
        };
        /**
         * @description The kind of activity_events row (design §10).
         * @enum {string}
         */
        ActivityEventType: "lesson_completed" | "exercise_submitted" | "exercise_returned" | "quiz_passed" | "course_enrolled" | "course_completed" | "degree_earned" | "badge_awarded";
        /** @description Minimal course context for rendering a feed entry. */
        ActivityCourseRef: {
            /** @description The course's slug */
            slug: string;
            /** @description The course's title */
            title: string;
        };
        /** @description Minimal lesson context for rendering a feed entry. */
        ActivityLessonRef: {
            /** @description The lesson's slug, unique within its course */
            slug: string;
            /** @description The lesson's title */
            title: string;
        };
        /** @description One activity_events row, joined with enough context to render. */
        ActivityEvent: {
            type: components["schemas"]["ActivityEventType"];
            /**
             * Format: date-time
             * @description When the event occurred, in UTC.
             */
            occurredAt: string;
            /** @description The related course, or null if this event type has none. */
            course: components["schemas"]["ActivityCourseRef"] | null;
            /** @description The related lesson, or null if this event type has none. */
            lesson: components["schemas"]["ActivityLessonRef"] | null;
        };
        /** @description One local calendar day's activity count. */
        HeatmapDay: {
            /** @description The local calendar date, YYYY-MM-DD. */
            date: string;
            /** @description Number of activity_events on this local day. */
            count: number;
        };
        /** @description The actor's activity heatmap: a contiguous run of local days plus derived streaks (design §10, §15). */
        Heatmap: {
            /** @description The timezone the days were bucketed in. */
            timezone: string;
            timezoneSource: components["schemas"]["TimezoneSource"];
            /** @description Contiguous local days, oldest first, ending today. */
            days: components["schemas"]["HeatmapDay"][];
            /** @description The highest single-day count in `days`, for scaling the intensity ramp. */
            maxCount: number;
            /** @description Current streak in local calendar days, computed fresh from activity_events. */
            currentStreak: number;
            /** @description Longest streak ever, in local calendar days, computed fresh from activity_events. */
            longestStreak: number;
        };
        /** @description A request to clone, validate, and import a content repo. */
        AdminImportRequest: {
            /** @description The repo's git URL. Only https:// and ssh:// remotes are accepted (git@host:path is accepted as ssh); file://, git://, http:// and git's ext:: transport are always refused — see clone.ts's assertAllowedRepoUrl. This refusal cannot be disabled through this endpoint under any circumstances. */
            url: string;
            /** @description Branch or tag to check out. Defaults to the repo's default branch. */
            ref?: string;
        };
        /**
         * @description One stage of the synchronous import pipeline (design §8).
         * @enum {string}
         */
        ImportStage: "cloning" | "validating" | "parsing" | "writing" | "done" | "failed";
        /** @description Per-entity outcome of one import. `archived` is always 0 for courses and tracks. */
        ImportEntityCounts: {
            created: number;
            updated: number;
            skipped: number;
            archived: number;
        };
        /** @description Every entity kind's outcome for one import. */
        ImportCounts: {
            courses: components["schemas"]["ImportEntityCounts"];
            tracks: components["schemas"]["ImportEntityCounts"];
            modules: components["schemas"]["ImportEntityCounts"];
            lessons: components["schemas"]["ImportEntityCounts"];
        };
        /** @description One line of the newline-delimited progress stream POST /api/v1/admin/imports returns. Only the fields relevant to `stage` are present on a given line — e.g. `problems` only appears on a 'failed' line, `counts` only on 'done'. */
        ImportProgressEvent: {
            stage: components["schemas"]["ImportStage"];
            /** @description A short human-readable description of what's happening at this stage. */
            message?: string;
            /** @description Present when stage is 'failed'. Every problem found, file:line formatted where applicable — the same list the CLI prints (design §8). */
            problems?: string[];
            /** @description The import_runs row this attempt was recorded under, once known. */
            importRunId?: string;
            /** @description Present when stage is 'done'. The imported course's slug. */
            slug?: string;
            /** @description Present when stage is 'done'. The commit the content was cloned at. */
            commitSha?: string;
            counts?: components["schemas"]["ImportCounts"];
        };
        /**
         * @description An import_runs row's status.
         * @enum {string}
         */
        ImportRunStatus: "running" | "success" | "failed";
        /** @description One import_runs row, for the admin history screen. */
        ImportRunSummary: {
            id: string;
            status: components["schemas"]["ImportRunStatus"];
            /** @description The content_repos URL this run came from, or null for a local-directory import. */
            repoUrl: ((string | null) | null) | null;
            /** @description The manifest's slug, when known — null only when the manifest itself couldn't be read (design §7's course_slug rationale). */
            courseSlug: ((string | null) | null) | null;
            commitSha: ((string | null) | null) | null;
            /** Format: date-time */
            startedAt: string;
            /**
             * Format: date-time
             * @description Null while status is 'running' (a process that died mid-import).
             */
            finishedAt: ((string | null) | null) | null;
            /** @description Present on a successful run, otherwise null. */
            counts: components["schemas"]["ImportCounts"] | null;
            /** @description The failure's summary message, or null on success. */
            error: ((string | null) | null) | null;
            /** @description The full file:line problem list for a failed run (design §8), or empty when there isn't one. */
            problems: string[];
        };
        /** @description Whether this instance has been claimed (design §5.2) */
        SetupStatus: {
            /** @description True once the first account has claimed the instance. */
            bootstrapped: boolean;
        };
        /** @description One half of the linked pair the bootstrap wizard creates */
        SetupAccount: {
            /** @description Lower-cased before storage; unique across the instance. */
            email: string;
            /** @description The profile handle (`/u/<handle>`), 2-31 characters of a-z, 0-9, hyphen or underscore. User-chosen and deliberately NOT derived from the email local part (design §11). */
            handle: string;
            /** @description At least 12 characters. Hashed with Argon2id (design §13) by the password-handling task; stored as NULL — meaning "no credential, cannot authenticate" — until that is wired in. */
            password: string;
            /** @description Optional human name shown on the profile. */
            displayName?: string | null;
        };
        /** @description The bootstrap wizard's submission (design §5.2) */
        SetupRequest: {
            /** @description The one-time token printed to the container logs on boot. Only its SHA-256 is stored, and it is destroyed by a successful claim. */
            setupToken: string;
            admin: components["schemas"]["SetupAccount"];
            student: components["schemas"]["SetupAccount"];
            /** @description An IANA time zone name applied to both accounts (design §15). */
            timezone?: string | null;
        };
        /** @description An account created by the bootstrap */
        SetupAccountResult: {
            /** Format: uuid */
            id: string;
            email: string;
            handle: string;
            displayName: string | null;
            /** @description The roles granted at creation. Roles are a set, not a ladder, and `admin` is exclusive of the other two (design §5, §5.1). */
            roles: ("student" | "teacher" | "admin")[];
        };
        /** @description The linked operator + student pair (design §5.2) */
        SetupResult: {
            admin: components["schemas"]["SetupAccountResult"];
            student: components["schemas"]["SetupAccountResult"];
        };
        /** @description An email/password sign-in attempt (design §13). */
        LoginRequest: {
            /** @description Case-insensitive; surrounding whitespace is trimmed server-side. */
            email: string;
            password: string;
            /** @description Optional human label for this device/session (design §13: "one per device"). A fresh login with the same label supersedes that device's previous session. */
            deviceLabel?: string | null;
        };
        /** @description The signed-in account, returned by login and refresh. Not the same shape as Me (design §15's learner profile) — this is the session's identity claim, roles included, and email/handle/displayName may be null exactly when the underlying users row has them unset. */
        AuthUser: {
            /** Format: uuid */
            id: string;
            email: ((string | null) | null) | null;
            handle: ((string | null) | null) | null;
            displayName: ((string | null) | null) | null;
            /** @description The actor's current roles, re-read from the database at login/refresh time (design §5.1: admin is exclusive). */
            roles: ("student" | "teacher" | "admin")[];
        };
        /** @description The body of a successful login or refresh. */
        AuthSessionResponse: {
            user: components["schemas"]["AuthUser"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in. Both session cookies are set. */
            200: {
                headers: {
                    /** @description learn_at (path=/) and learn_rt (path=/api/v1/auth), both httpOnly, Secure, SameSite=Lax. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            /** @description email and/or password missing, or the password exceeds the length limit. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid email or password. Identical body and status whether the account does not exist, the password is wrong, or the account has no credential at all — see the operation description. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too many login attempts for this IP or account. `Retry-After` carries the number of seconds until the next attempt may proceed. */
            429: {
                headers: {
                    /** @description Seconds until the caller may try again. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A fresh session. Both cookies are re-set. */
            200: {
                headers: {
                    /** @description learn_at (path=/) and learn_rt (path=/api/v1/auth), both httpOnly, Secure, SameSite=Lax. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            /** @description No refresh cookie, or it is unknown, expired, revoked, or reused. Both session cookies are cleared on this response. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. Both session cookies are cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every session is revoked. The caller's own cookies are cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session — refused by can(), same as any other protected route. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseSummary"][];
                };
            };
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseDetail"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    patchCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoursePatchRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseManage"];
                };
            };
            /** @description Neither field was provided, or a field's value is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The actor may not make this change */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Course not found — also returned for a hidden course the actor cannot discover, rather than 403 (design §12: a 403 would confirm the course exists). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCourseManage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseManage"];
                };
            };
            /** @description Not found, or not visible to this actor as a manager */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createEnrolment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enrolled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enrolment"];
                };
            };
            /** @description Refused — not eligible (wrong visibility, or an admin, who can never enrol) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Course not found, or hidden and undiscoverable to this actor */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteEnrolment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not enrolled (either just withdrawn, or already wasn't) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enrolment"];
                };
            };
            /** @description Refused by the current policy check */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    upsertLessonProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
                /** @description The lesson slug (unique within the course) */
                lessonSlug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProgressUpsertRequest"];
            };
        };
        responses: {
            /** @description Progress recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonProgressDetail"];
                };
            };
            /** @description Course or lesson not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The lesson's kind cannot be marked complete directly (only kind "lesson" can — exercises and quizzes complete through other mechanisms). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    submitQuizAttempt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
                /** @description The lesson slug (unique within the course) */
                lessonSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizSubmitRequest"];
            };
        };
        responses: {
            /** @description Scored result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizSubmitResult"];
                };
            };
            /** @description answers is missing or malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Course or lesson not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description This lesson is not kind "quiz" */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCourseProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Progress summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseProgressSummary"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The actor's profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdateRequest"];
            };
        };
        responses: {
            /** @description Profile updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description timezone is missing or not a real IANA zone name */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMyActivity: {
        parameters: {
            query?: {
                /** @description Max events to return. Defaults to 20, clamped to [1, 100]. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The activity feed, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityEvent"][];
                };
            };
        };
    };
    getMyHeatmap: {
        parameters: {
            query?: {
                /** @description Trailing window size in weeks (7 days each), ending today. Defaults to 53, clamped to [1, 53]; narrower clients request fewer (design §10: ~13 on phone, ~26 on tablet). */
                weeks?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The heatmap */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Heatmap"];
                };
            };
        };
    };
    getCourseLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The course slug */
                courseSlug: string;
                /** @description The lesson slug (unique within the course) */
                lessonSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lesson found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lesson"];
                };
            };
            /** @description Course or lesson not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createAdminImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminImportRequest"];
            };
        };
        responses: {
            /** @description A stream of newline-delimited ImportProgressEvent objects, one per line, ending with a 'done' or 'failed' event. Always 200: the HTTP status is set before the outcome of the import is known, since the import result arrives inside the stream body, not the status line. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": components["schemas"]["ImportProgressEvent"];
                };
            };
            /** @description url is missing/empty, or ref is present and not a string */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The actor is not permitted to import content repos */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAdminImportRuns: {
        parameters: {
            query?: {
                /** @description Max runs to return. Defaults to 20, clamped to [1, 100]. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The import run history, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRunSummary"][];
                };
            };
            /** @description The actor is not permitted to read import history */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The instance's bootstrap state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    createSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description The instance is claimed; the operator + student pair exists */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupResult"];
                };
            };
            /** @description The request body is malformed — bad email, non-URL-safe or reserved handle, short password, invalid timezone, or the two accounts sharing an email or handle. The claim is untouched. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Wrong, tampered or absent setup token. The claim is NOT consumed — the correct token still works afterwards. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The instance was unclaimed when this request arrived, and a concurrent request won the race. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The instance was already set up before this request arrived. Permanent. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
